package com.xavierloeraflores.inventorymanagement;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.Objects;
import java.util.Optional;
import java.util.ResourceBundle;

/**
 * Controller class for the ModifyPart.fmxl form.
 * Implements Initializable
 * @author xavierloeraflores
 */
public class ModifyPartController implements Initializable {
    /**
     * The [selectedPart] which will be modified by the user.
     */
    private Part selectedPart;
    /**
     * The [radioInHouse] which allows the user to select an In House Part.
     */
    @FXML
    private RadioButton radioInHouse;
    /**
     * The [radioOutsourced] which allows the user to select an Outsourced Part.
     */
    @FXML
    private RadioButton radioOutsourced;
    /**
     * The [fieldID] which displays the id for the Part .
     */
    @FXML
    private TextField fieldId;
    /**
     * The [fieldName] takes in input from the user for the partName.
     */
    @FXML
    private TextField fieldName;
    /**
     * The [fieldStock] takes in input from the user for the Part inventory or partStock.
     */
    @FXML
    private TextField fieldStock;
    /**
     * The [fieldPrice] takes in input from the user for the partPrice.
     */
    @FXML
    private TextField fieldPrice;
    /**
     * The [fieldMin] takes in input from the user for the partMin.
     */
    @FXML
    private TextField fieldMin;
    /**
     * The [fieldMax] takes in input from the user for the partMax.
     */
    @FXML
    private TextField fieldMax;
    /**
     * The [labelSpecial] which displays whether the user should enter a machineId or companyName.
     */
    @FXML
    private Label labelSpecial;
    /**
     *  The [fieldSpecial] takes in input from the user for both machineId and companyName.
     */

    @FXML
    private TextField fieldSpecial;
    /**
     * The [isOutsourced] boolean which indicates if the Part is Outsourced or In House.
     */
    private boolean isOutsourced;
    /**
     * The [errorMessage] which will be displayed in case of an error when validating.
     */
    private String errorMessage;
    /**
     * The autogenerated [partId] of the Part to be added.
     */
    private int partId;

    /**
     * When the user presses the In House radio button, the Part will convert to an InHouse Part type
     * @param actionEvent JavaFX action event
     */
    @FXML
    private void setRadioInHouse(ActionEvent actionEvent) {
        isOutsourced = false;
        labelSpecial.setLayoutX(14.0);
        labelSpecial.setText("Machine ID");
        radioOutsourced.setSelected(false);
    }

    /**
     * When the user presses the Outsourced radio button, the Part will convert to an Outsourced Part type
     * @param actionEvent JavaFX action event
     */
    @FXML
    private void setRadioOutsourced(ActionEvent actionEvent) {
        isOutsourced = true;
        labelSpecial.setLayoutX(-8.0);
        labelSpecial.setText("Company Name");
        radioInHouse.setSelected(false);
    }
    /**
     * Returns the user back to the main screen.
     * @param actionEvent JavaFX action event
     * @throws IOException
     */
    private void mainScreen(ActionEvent actionEvent) throws IOException{
        Parent mainFXML = FXMLLoader.load(getClass().getResource("Main.fxml"));
        Scene mainScene = new Scene(mainFXML);
        Stage stage = (Stage) ((Node) actionEvent.getSource()).getScene().getWindow();
        stage.setTitle("Inventory Management System");
        stage.setScene(mainScene);
        stage.show();
    }


    /**
     * Validates whether the inputs the user has provided are valid for creating a new part.
     * RUNTIME ERROR: errorMessage was not updating with the concat function.
     * @param name [String] name value from the name field
     * @param priceString [String] price value from the price field
     * @param stockString [String] stock value from the inventory/stock field
     * @param minString [String] min value from the min field
     * @param maxString [String] max value from the max field
     * @param special [String] special value from the special field
     * @param isOutsourced [Boolean] values as a result of the radio buttons
     * @return [Boolean] true if the inputs are valid, false if any of the inputs are not valid
     */
    private boolean validate(String name,  String priceString, String stockString, String minString, String maxString, String special, boolean isOutsourced ){
        boolean validated = true;
        errorMessage = "";

        if(Objects.equals(name, "")){
            validated = false;
            errorMessage=errorMessage.concat("\nName field can not be empty.");
        }
        if(Objects.equals(priceString, "")){
            validated = false;
            errorMessage=errorMessage.concat("\n Price field can not be empty.");
        }
        if(Objects.equals(stockString, "")){
            validated = false;
            errorMessage=errorMessage.concat("\n Stock field can not be empty.");
        }
        if(Objects.equals(minString, "")){
            validated = false;
            errorMessage=errorMessage.concat("\n Min field can not be empty.");
        }
        if(Objects.equals(maxString, "")){
            validated = false;
            errorMessage=errorMessage.concat("\n Max field can not be empty.");
        }
        if(Objects.equals(special, "")){
            validated = false;
            errorMessage=errorMessage.concat("\n Company name or machine Id can be empty.");
        }
        if(!validated){return false;}

        int stock =0;
        int min =0;
        int max=0;
        double price=0.0;
        int specialInt=0;


        try{

            try {stock= Integer.parseInt(stockString);}
            catch (NumberFormatException e){
                validated = false;
                errorMessage=errorMessage.concat("\n Part must have an valid stock integer value");
            }

            try {min = Integer.parseInt(minString);}
            catch (NumberFormatException e){
                validated = false;
                errorMessage=errorMessage.concat("\n Part must have an valid integer value");
            }

            try {max= Integer.parseInt(maxString);}
            catch (NumberFormatException e){
                validated = false;
                errorMessage=errorMessage.concat("\n Part must have an valid Max integer value ");
            }

            try {price= Double.parseDouble(priceString);}
            catch (NumberFormatException e){
                validated = false;
                errorMessage=errorMessage.concat("\n Part must have an valid Price double value ");
            }

            try {if (!isOutsourced){specialInt= Integer.parseInt(special);}}
            catch (NumberFormatException e){
                validated = false;
                errorMessage=errorMessage.concat("\n In house part must have an ID value number");
            }

        }catch (Exception e){
            return false;
        }




        if (stock < 0){
            validated = false;
            errorMessage=errorMessage.concat("\n Stock can not be negative.");
        }
        if (stock < min){
            validated = false;
            errorMessage=errorMessage.concat("\nStock must be within range of min & max \nStock can not be less than min.");
        }
        if (stock > max){
            validated = false;
            errorMessage=errorMessage.concat("\nStock must be within range of min & max \n Stock can not be more than max.");
        }

        if(max < min){
            validated = false;
            errorMessage=errorMessage.concat("\n Max can not be less than min.");
        }
        if(min < 0){
            validated = false;
            errorMessage=errorMessage.concat("\n Min can not be less than 0.");
        }
        if(price < 0){
            validated = false;
            errorMessage=errorMessage.concat("\n Price must be a positive number.");
        }
        if(Objects.equals(name, "")){
            validated = false;
            errorMessage=errorMessage.concat("\n Name field must not be empty.");
        }
        if (specialInt<0){
            validated = false;
            errorMessage=errorMessage.concat("\n In house part must have an ID value number");
        }


        return validated;
    }

    /**
     * Handles the saving functionality when a user presses the save button.
     * If the inputs are valid, the Part is added to the Inventory.
     * @param actionEvent JavaFX action event
     * @throws IOException
     */
    @FXML
    private void handleSave(ActionEvent actionEvent) throws IOException {
        String partName = fieldName.getText();
        String partStock = fieldStock.getText();
        String partPrice = fieldPrice.getText();
        String partMin = fieldMin.getText();
        String partMax = fieldMax.getText();
        String partSpecial = fieldSpecial.getText();

        try {
            if(validate(partName, partPrice, partStock, partMin,partMax,partSpecial,isOutsourced)){
                String name = partName;
                int stock = Integer.parseInt(partStock);
                double price = Double.parseDouble(partPrice);
                int min = Integer.parseInt(partMin);
                int max = Integer.parseInt(partMax);
                Part newPart;

                if (!isOutsourced) {
                    int machineId = Integer.parseInt(partSpecial);
                    newPart = new InHouse(partId, name, price, stock, min, max,machineId);
                } else {
                    String companyName = partSpecial;
                    newPart = new Outsourced(partId, name, price, stock, min, max, companyName);
                }
                int index = Inventory.getAllParts().indexOf(selectedPart);
                Inventory.updatePart(index, newPart);
                mainScreen(actionEvent);

            }
            else{
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setTitle("Error");
                alert.setHeaderText("Error Adding Part");
                alert.setContentText(errorMessage);
                alert.showAndWait();
            }
        }
        catch(NumberFormatException exception) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText("Error Adding Part");
            alert.setContentText("An error has occurred");
            alert.showAndWait();
        }
    }

    /**
     * Handles the canceling functionality when a user presses the cancel button.
     * It will return the user the Main screen if the user confirms cancellation
     * @param actionEvent Java FX Action event
     * @throws IOException
     */
    @FXML
    private void handleCancel(ActionEvent actionEvent) throws IOException {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
        alert.initModality(Modality.NONE);
        alert.setTitle("Cancel Add Part Confirmation");
        alert.setHeaderText("Confirm Cancellation");
        alert.setContentText("Are you sure you want to cancel adding this part?");
        Optional<ButtonType> result = alert.showAndWait();

        if (result.get() == ButtonType.OK) {mainScreen(actionEvent);}
        else {System.out.println("Add Part Cancel has been denied.");}
    }

    /**
     * Initializes the FXML Screen, sets the part to InHouse, & generates a partId.
     * @param url parameter for the FXML Screen
     * @param rb parameter for the FXML Screen
     */
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        selectedPart = MainFormController.getSelectedPart();
        System.out.println(selectedPart.getName());
        if(selectedPart instanceof Outsourced){
            radioOutsourced.setSelected(true);
            isOutsourced = true;
            labelSpecial.setLayoutX(-8.0);
            labelSpecial.setText("Company Name");
            radioInHouse.setSelected(false);
            fieldSpecial.setText(((Outsourced) selectedPart).getCompanyName());
        }
        if(selectedPart instanceof InHouse){
            radioInHouse.setSelected(true);
            isOutsourced = false;
            labelSpecial.setLayoutX(14.0);
            labelSpecial.setText("Machine ID");
            radioOutsourced.setSelected(false);
            fieldSpecial.setText(Integer.toString(((InHouse) selectedPart).getMachineId()));
        }

        partId = selectedPart.getId();
        fieldName.setText(selectedPart.getName());
        fieldStock.setText(Integer.toString(selectedPart.getStock()));
        fieldPrice.setText(Double.toString(selectedPart.getPrice()));
        fieldMin.setText(Integer.toString(selectedPart.getMin()));
        fieldMax.setText(Integer.toString(selectedPart.getMax()));
        fieldId.setText(Integer.toString(partId));
    }
}
